apiVersion: v1
kind: Pod
metadata:
  name: fs-etl-pod
spec:
  containers:
    - name: fs-etl-container
      image: mlops-docker-snapshots.binary.alfabank.ru/ubuntu_with_python:latest
      ports:
        - containerPort: 8150

      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-admin
#  namespace: default
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io