dags:
  persistence:
    enabled: true
    existingClaim: host-dags-pvc
  gitSync:
    enabled: false


logs:
  persistence:
    enabled: true

airflow:
  image:
    repository: mlops-docker-snapshots.binary.alfabank.ru/airflow_fs_etl
    tag: v0.8.1
#    repository: mlops-docker-snapshots.binary.alfabank.ru/fs_etl_basic
#    tag: latest
#    pullPolicy: IfNotPresent
  executor: KubernetesExecutor

workers:
  enabled: false

flower:
  enabled: false

redis:
  enabled: false

scheduler:
  logCleanup:
    enabled: false