apiVersion: v1
kind: Pod
metadata:
  name: fs-etl-pod
spec:
  volumes:
  - name: code-storage
    persistentVolumeClaim:
      claimName: code-pvc
  containers:
    - name: fs-etl-container
      image: mlops-docker-snapshots.binary.alfabank.ru/ubuntu_with_python:latest
      ports:
        - containerPort: 8150

      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - mountPath: "/code"
          name: code-storage
