apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
#  labels:
#    name-label: nginx-label
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80