version: "3"

services:
#   cassandra:
#     image: cassandra
#     hostname: cassandra
#     volumes:
#       - ./data/cassandra:/var/lib/cassandra
#     ports:
#       - "9042:9042"
#       - "7000:7000"
#
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#      - "6380:6380"
#    hostname: redis
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#      - "./data/redis:/data"
#    command: redis-server --save 60 1 --loglevel warning

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#   dns:
#     depends_on:
#       - postgres
# #      - redis
#       - cassandra
#     hostname: dns
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock"
#       - "/etc/resolv.conf:/etc/resolv.conf"
#     image: defreitas/dns-proxy-server
